Refact/keyple v2
calypsonet/keyple-java-demo-remote pull request #12
Opened 2021-07-29 11:53 UTC by ocfmem

2021-07-29 12:39 UTC, andrei-cristea requested changes

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/README.md
>  # Keyple Remote Demo - Android Client's repository
Personnellement, je pense qu'il faut utiliser le terme "distributed" à la place de "remote" pour le nom du repo et dans le reste de la documentation.

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/build.gradle
> +    implementation("org.eclipse.keyple:keyple-plugin-java-api:$keypleVersion")
Supprimer cette dépendance.

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/build.gradle
> +    implementation("org.eclipse.keyple:keyple-service-java-lib:$keypleVersion")
Pour prendre les bonnes habitudes, il ne faut pas utiliser de variable de version Keyple globale car chaque module à son propre cycle de vie.

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/eclipse/keyple/demo/remote/ui/CardReaderActivity.kt
> +                    transactionManager,
Le paramètre "initialCardContent" doit être de type "SmartCard".

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/eclipse/keyple/demo/remote/ui/ChargeActivity.kt
> +                    transactionManager,
Le paramètre "initialCardContent" doit être de type "SmartCard".

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/eclipse/keyple/demo/remote/ui/ChargeActivity.kt
> +                    transactionManager,
Le paramètre "initialCardContent" doit être de type "SmartCard".

2021-07-29 12:39 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/eclipse/keyple/demo/remote/ui/PersonnalizationActivity.kt
> +                    transactionManager,
Le paramètre "initialCardContent" doit être de type "SmartCard".

2021-09-15 10:45 UTC, andrei-cristea requested changes
Il serait bien d'exécuter la tâche spotless.

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/README.md
> +    implementation "org.eclipse.keyple:keyple-service-java-lib:2.0.+"
Le + ne doit être utilisé que pour les APIs.

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/README.md
> +    implementation "org.eclipse.keyple:keyple-util-java-lib:2.0.+"
Pour la lib util qui est une exception, c'est 2.+ et non 2.0.+

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/README.md
> +    implementation "org.eclipse.keyple:keyple-plugin-android-nfc-java-lib:2.0.+"
idem

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/calypsonet/keyple/demo/distribued/ui/CardReaderActivity.kt
> +                    transactionManager,
Il faut envoyer un SmartCard et non un CardTransactionManager

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/calypsonet/keyple/demo/distribued/ui/ChargeActivity.kt
> +                    transactionManager,
idem

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/calypsonet/keyple/demo/distribued/ui/ChargeActivity.kt
> +                    transactionManager,
idem

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/app/src/main/kotlin/org/calypsonet/keyple/demo/distribued/ui/PersonnalizationActivity.kt
> +                    transactionManager,
idem

2021-09-15 10:45 UTC, andrei-cristea commented on client/android/build.gradle
> +    keypleVersion = '2.0.0-rc4'
C'est une erreur car tous les modules ne sont pas en rc4

2021-09-15 10:45 UTC, andrei-cristea commented on server/build.gradle
> +    implementation group: 'org.eclipse.keyple', name: 'keyple-card-calypso-java-lib', version: keyple_v,  changing: true
Ne pas utiliser de version globale Keyple

2021-09-15 10:45 UTC, andrei-cristea commented on server/gradle.properties
> +keyple_version=2.0.0-SNAPSHOT
il faut supprimer le keyple_version

2021-09-21 15:40 UTC, ocfmem commented on client/android/app/build.gradle
> +    implementation("org.eclipse.keyple:keyple-plugin-java-api:$keypleVersion")
org.eclipse.keyple:keyple-plugin-java-api ?

2021-11-26 14:56 UTC, merged